name: Deploy Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install "mkdocs-material==9.5.18" "mkdocs-minify-plugin==0.8.0"
      - run: mkdocs gh-deploy --force
        working-directory: docs
